### PR TITLE
Fossconf23

### PR DESCRIPTION
**Pull request by adityaslyf**

### CODE REVIEW

**Comment by adityaslyf** [comment]
Updated the status of tickets, registrations, and volunteer applications on the website.

**Comment by codecShivam** [comment]
> Updated the status of tickets, registrations, and volunteer applications on the website.

Hey @adityaslyf, thanks for the update! 

Before merging, please address this remaining tasks:

- **Prevent direct file access:** Astro automatically creates routes for files in the src/pages directory
    - Choose one of the following methods to prevent direct access to files in `src/pages` via URL:
        - Move the file outside of `src/pages`
        - Implement a redirect to a different page
        - Customize routing configuration (if advanced control is needed)

Please commit these changes within this PR itself, no need for a separate one.

**Comment by adityaslyf** [comment]
@codecShivam Sure I will fix this asap

**Comment by SAMAD101** [comment]
lgtm

**Comment by SAMAD101** [comment]
> @codecShivam Sure I will fix this asap

Whats the status dude

**Comment by codecShivam** [comment]
The new commits have resolved this issue. @samad101, @adityaslyf

**Pull request closed without merging**
